"""make vehicle.name NOT NULL (fill existing values)

Revision ID: 24c25e107a1b
Revises: bf4c4407888f
Create Date: 2026-01-04 22:20:49.283694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c25e107a1b'
down_revision = 'bf4c4407888f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Fill existing NULL names with a unique placeholder using the id to avoid unique constraint violations
    op.execute("UPDATE vehicle SET name = 'UNKNOWN_' || id WHERE name IS NULL")
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
