"""add vehicle.name nullable True

Revision ID: bf4c4407888f
Revises: a0535cfbb2de
Create Date: 2026-01-04 22:18:04.966555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4c4407888f'
down_revision = 'a0535cfbb2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
